### PR TITLE
Aded newdata entry form

### PR DESCRIPTION
**Pull request by izwick-schachter**
@ArtOfCode- Would you mind looking over this and possibly rails-ify it? This uses a one page, JS solution. Not sure about mobile compatibility or noscript compatibility, but for now it should work.

### CODE REVIEW

**Comment by ArtOfCode-** [comment]
No need for this to be a JS solution, we can do it all with forms and server side to maximise compatibility.

**Comment by izwick-schachter** [comment]
Yeah, but if we just stick a giant form around the whole body it'll work on mobile and in noscript.

**Comment by ArtOfCode-** [comment]
I'd prefer to do it in stages, as we did with the Sinatra app - on the basis that even some info is useful, even if you don't have time or battery to put it all in. The easiest way of doing that while remaining noscript and mobile compatible is just not to use JS - use multiple form stages with server actions instead.

**Comment by izwick-schachter** [comment]
Yeah, it still will push the data to the server after each step. It's just smoother for the user, because there aren't new page loads. After they click on the map, a new RescueRequest is created. After the fill in the short fields, they get updated in the server. Same after the long fields. The only issue is for clients that have limited JS support, and in that case the whole gmaps thing won't work and on the old app, they'd never get pushed from stage 1 to 2.

**Pull request merged**
